apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
      env: test
  template:
    metadata:
      labels:
        app: medicure
        env: test
    spec:
      containers:
      - name: medicure
        image: medicure:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-test
spec:
  type: NodePort
  selector:
    app: medicure
    env: test
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
